### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by r0ptr** [ionescu007/minlzma#9]
Hello!

This is not an issue, but more of a usage question. Looking at the API of the library and the sample application, I can see that it reads from an input buffer and decompresses into a single output buffer. Does it mean that it supports only archives that contain a single file, or just that the library is concerned only with decompression of lzma streams, and delegates the task of archive processing (traversing the container to get all entries) to the user / another library? If that's the case, any recommendation on with which libraries have you used it successfully to say, combine it and provide a full-featured extractor that supports multiple files as well?

Thanks!

**Comment by ionescu007** [comment]
Hi!

Correct, the library only deals with XZ streams, which only support a single file, and not 7zip archives. You could, I imagine take the 7Z SDK, and replace the LZMA decoder with my library instead. I don't have any other specific extractors I can think of, sorry :(
